### ISSUE TITLE
VS2019  Chinese fonts are not supported

### ISSUE THREAD

**Issue by aiyogege** [Immediate-Mode-UI/Nuklear#218]
The same code vs2017 can display Chinese, vs2019 display garbled code！

![2017](https://user-images.githubusercontent.com/51818119/100171999-58baa880-2f02-11eb-902f-f1689d89cb83.png)
![2019](https://user-images.githubusercontent.com/51818119/100172005-5b1d0280-2f02-11eb-8fb5-05aa8d1fe465.jpg)

**Comment by aiyogege** [comment]
It has been solved, and the specific reason is unknown

**Comment by user23333** [comment]
> It has been solved, and the specific reason is unknown

老哥怎么解决得

**Comment by 00BUG00** [comment]
怎么解决的,能说一下吗

**Comment by user23333** [comment]
> 怎么解决的,能说一下吗

把nuklear.h 16714行的
`
if (!pc->x0 && !pc->x1 && !pc->y0 && !pc->y1) continue;
`
改成
`
if (!pc->x0 && !pc->x1 && !pc->y0 && !pc->y1) { glyph_count++; continue; }
`

**Comment by 00BUG00** [comment]
十分感谢  成了

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2021年10月30日 20:33
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Immediate-Mode-UI/Nuklear] VS2019 Chinese fonts are not supported (#218)


怎么解决的,能说一下吗

把nuklear.h 16714行的
if (!pc->x0 && !pc->x1 && !pc->y0 && !pc->y1) continue;
改成
if (!pc->x0 && !pc->x1 && !pc->y0 && !pc->y1) { glyph_count++; continue; }

―
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FImmediate-Mode-UI%2FNuklear%2Fissues%2F218%23issuecomment-955202316&data=04%7C01%7C%7C00a59ab1b4ef4294c7b908d99ba177e6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637711940088684140%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RXIns%2B1CZx5TF6JQhre0w9v9X6md%2FSKcT0RG5S9GA2c%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALN7WPFL2BUVXIYZS6JXVILUJPQZJANCNFSM4UBVQROA&data=04%7C01%7C%7C00a59ab1b4ef4294c7b908d99ba177e6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637711940088684140%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=S745jObfaRaUXxoPu5C%2FKCb%2BE3nosWvYGv0PKPA%2FAjU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C00a59ab1b4ef4294c7b908d99ba177e6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637711940088694107%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Aob8mQ9F6zlOaOsq%2FS9mawNACyEC352IRVNsDm0PoaM%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C00a59ab1b4ef4294c7b908d99ba177e6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637711940088694107%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DUMkx2TO9sjYgCmO3cguUs2lnFb9K%2FWh%2FhmLXrV8uzo%3D&reserved=0>.

**Comment by 00BUG00** [comment]
大佬 问一下  nuklear + glfw 创建文本编辑框时  通过BACKSPACE按键删除字符时,会同时删除多个字符,这个问题你遇到过吗?

**Comment by aiyogege** [comment]
不晓得，我换回imgui了，这玩意不支持复制黏贴就不用了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月3日(星期五) 凌晨2:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Immediate-Mode-UI/Nuklear] VS2019  Chinese fonts are not supported (#218)





 大佬 问一下  nuklear + glfw 创建文本编辑框时  通过BACKSPACE按键删除字符时,会同时删除多个字符,这个问题你遇到过吗? 
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
