### ISSUE TITLE
its not actually an issue. i just want ask something important

### ISSUE THREAD

**Issue by Parad0x84** [Immediate-Mode-UI/Nuklear#261]
i want learn a graphic library for using in pure C or C++. i have a few questions about it.
is Nuklear worth to learn with ignoring popular libraries like OpenGL or GTK+? is it have support if i get errors or cant handle something?

Can you suggest me one of this libraries? it depends on which OS's are supported and which programming languages can be use (its because in future i can decide to learn more programming languages).

sory for opening issue but i cant see discussions here.

**Comment by dumblob** [comment]
I'm getting notifications from this repo (as one of it's contributors), but I can't answer most of them due to my lack of time.

Anyway, Nuklear builds more on the ideas & approaches from the game industry (both mobile & desktop). If you want to learn how UIs (might) work in games (disregarding whether 2D or 3D), this is a very good starting option. If you're looking for full-featured, fatty UI library, then I'd slightly discourage you to use any of Nuklear, ImGUI, etc. and rather go for Qt, GTK, wxWidgets etc. If you're looking for **learning** how these fatty UI libraries are built (i.e. event loop and its pros/cons, "signals"/callbacks, draw buffers, positioning of widgets, multithreading, etc.), then Nuklear is IMHO still a very good option (probably better than reading the source of GTK/QT/...).

I hope others can answer more thoroughly if they find more time than me :wink:.

**Comment by Parad0x84** [comment]
> I'm getting notifications from this repo (as one of it's contributors), but I can't answer most of them due to my lack of time.
> 
> Anyway, Nuklear builds more on the ideas & approaches from the game industry (both mobile & desktop). If you want to learn how UIs (might) work in games (disregarding whether 2D or 3D), this is a very good starting option. If you're looking for full-featured, fatty UI library, then I'd slightly discourage you to use any of Nuklear, ImGUI, etc. and rather go for Qt, GTK, wxWidgets etc. If you're looking for **learning** how these fatty UI libraries are built (i.e. event loop and its pros/cons, "signals"/callbacks, draw buffers, positioning of widgets, multithreading, etc.), then Nuklear is IMHO still a very good option (probably better than reading the source of GTK/QT/...).
> 
> I hope others can answer more thoroughly if they find more time than me 😉.

thanks for your answer. i think you clearly explain everything except one thing:
How important to learnig how these UI libraries are built. What im gonna lose if i just use library.
Have a great day. Thx again

**Comment by riri** [comment]
You don't need to learn the internal of those libraries if you just want to be a user of them (consume what is provided). But like all piece of software, even famous libraries have problems (issues or design limits), so it's always better to have at least a bird view of how they work internally (plus that will help you using them efficiently).

Nuklear is clearly not of the same world than Qt, Gtk+, Juce (although one can make a desktop app with it, it's not its intent). It's also a "library" standing on simplicity and lightness. That also means features are missing, often because they can be implemented by users themselves with the basic bricks of Nuklear.

OpenGL is not a GUI library, it's an API to communicate with the GPU (and do 3D). Nuklear (like many other game oriented libs) uses it for most of its rendering backends (the demo directory).

Hope this helped :)

**Comment by RobLoach** [comment]
Thanks all!
