### ISSUE TITLE
Discussions area

### ISSUE THREAD

**Issue by riskpeep** [Immediate-Mode-UI/Nuklear#264]
Would the maintainers have any interest in enabling the discussions area for the project?  I've got a raft of questions about how to use and I'd be interested to collaborate w/o opening issues for every question.

It would be nice to be able to build up a body of knowledge about how to use the project.

(e.g. How to make keyboard events work for widgets)

**Comment by dumblob** [comment]
I for myself would prefer staying with just "Issues" - first, one has everything on the first glance (besides this is a small project, so no need to divide everything into groups etc.).

Second, usually questions and issues (technical ones) overlap or change to/from to another over time (so it's much better to use labels instead of completely separate functionality).

Third, links from/to Discussions are not shown in Issues and vice versa (this is really a wtf thing when I found out and because not just my feelings, but also research has shown, that people remember **always** only through graph of related information, then a missing "link" is the absolutely worst thing to do).

**Comment by riskpeep** [comment]
@dumblob, thank you for this response.  It is really helpful (believe it or not) and we'll reasoned.  I'll post questions here in addition to issues.
