### ISSUE TITLE
Suspicious trivial expression `x2-x2` in `stbtt__fill_active_edges_new`

### ISSUE THREAD

**Issue by arseniy-sonar** [Immediate-Mode-UI/Nuklear#268]
Hello, this line seems to do a useless computation `x2-x2`, which might be not the intention:
https://github.com/Immediate-Mode-UI/Nuklear/blob/4a749821c46865e9592fe1437638d89f1b3409da/src/stb_truetype.h#L3172
Unfortunately, I struggle to understand the code to propose a fix, so just reporting it as I found it.

**Comment by trbednarzyk** [comment]
`stb_truetype.h` comes from [nothings/stb](https://github.com/nothings/stb), a public domain collection of single-file libraries. As it turns out, this exact issue was already created on that repo [here](https://github.com/nothings/stb/issues/924), though there hasn't been any activity on it since it was created. You should probably close this Nuklear issue as this is not a (potential) issue with Nuklear itself, but rather with stb.
