### ISSUE TITLE
False claims and multitude of issues

### ISSUE THREAD

**Issue by gek169** [Immediate-Mode-UI/Nuklear#272]
Nuklear has the following major issues:
1) It requires loading TTF fonts to initialize. This makes it a non-sequitur in embedded systems design and is totally nonsensical in, say, textmode. It's bloat, it's stupid, and ultimately, on every single target platform, the user will have their own way of rendering fonts. There is no reason for you to provide your own which is not cross platform and inherently restrictive.
2) The set of functions you must implement for a particular graphics library is poorly documented. What are the drawing primitives I must implement?
What are their syntax?

I know I could comb through your source code and *figure out* what I have to implement, but the fact that I have to ask indicates a major problem with your library.

Ultimately, you need only TWO primitives to implement a complete gui, all elements can be customized through a "hints" system which is implementation specific:

* Box

* Text Box

Scroll bars, clickable tick boxes, images, windows, etcetera are just variations or combinations of these.

3) The library is about as "header only" as OpenGL- There is no cross-platform internal implementation (For instance, to an internal framebuffer, which would be wonderful, or to the commandline, which would at least be functional) but rather an external .c file must be provided for the GUI implementation. I'd call this *false advertising* and I think you should remove the "header only" claim from your page, or at the very least, make it clearer than any usable form of nuklear will require implementations of its predeclared functions.

4) Total lack of keyboard/gamepad input type support
There seems to be no way in your demos to navigate the menus using the keyboard only, which just goes further in proving my point that your library sucks.
Imagine that someone wanted to control your GUI on a game console or DVD player. What are they supposed to do?

I mashed every button on my keyboard in your example programs and absolutely nothing happened. There is no way to navigate the menus without a mouse or touchscreen.

5) Overselling and improper labelling
Overall, you oversell the library. Somehow, it's "cross platform" and "c89" but it requires an RGBA display and the ability to render TTF fonts. Already, it can't run on a machine manufactured before 1999. Already, it's completely outmoded in its target market by larger, more feature-rich GUI toolkits.

To make Nuklear truly useful, you MUST provide workaround paths for systems without support for...
* Line rendering
* TTF Font rendering
* Image rendering

Currently, the only use case I can see for Nuklear is embedding into programs which could already use superior GUI toolkits.

Nuklear's only use case is for C hipsters to say they aren't using QT.

For an Immediate mode GUI standard which *IS* actually fully cross platform, and actually does provide very clear, direct documentation of its features and functionality, and how to implement them, see:

https://github.com/gek169/OpenIMGUI_Standard

**Comment by tombish** [comment]
Are you for real?.. do you expect others to do everything for you?

Perhaps you should actually read the documentation before posting this dross.

**Comment by NightYoshi370** [comment]
> I know I could comb through your source code and figure out what I have to implement, but the fact that I have to ask indicates a major problem with your library.

library's documentation*. There's a difference between a library and its docs.

> which just goes further in proving my point that your library sucks.

That comment was really not needed. Also, there's a difference between demos and library.

> Currently, the only use case I can see for Nuklear is embedding into programs which could already use superior GUI toolkits.

So why not use those instead of insulting this left and right? There's a difference between constructive criticism and just insults. You've done the latter.

**Comment by Hejsil** [comment]
I recommend having a look around for other immediate-mode gui that suits your needs better. We don't really have the contributors available to make big architectural changes. So unless you intend to spearhead the effort of improving Nuklear for your needs, there is not much that can be do.

Best of luck :)

**Comment by gek169** [comment]
> > I know I could comb through your source code and figure out what I have to implement, but the fact that I have to ask indicates a major problem with your library.
> 
> library's documentation*. There's a difference between a library and its docs.
> 
> > which just goes further in proving my point that your library sucks.
> 
> That comment was really not needed. Also, there's a difference between demos and library.
> 
> > Currently, the only use case I can see for Nuklear is embedding into programs which could already use superior GUI toolkits.
> 
> So why not use those instead of insulting this left and right? There's a difference between constructive criticism and just insults. You've done mainly the latter.

The problem is that you're claiming A, but you're actually B

if this was selling itself as a small QT replacement? Fine.

It's selling itself as a "low dependencies single-header minimal C89 GUI library" 

which uh... it is NOT

And yes it deserves insults because the fact that you're claiming this means that nobody has actually written the real solution- a fake solution exists, and it convinces people into believing the problem is solved. why write a real one?

**Comment by gek169** [comment]
Constructive criticism?
Write a backend to write into a raw framebuffer given an array of pixels. Let me control how user input is polled and feed it into the library.

Don't require a ttf font to be loaded. I've got a perfectly good 8x8 public domain header-only bitmap ascii font just for you:

https://github.com/dhepper/font8x8

That's the least you could do.

if you can't do that, then remove the claim that this is a "minimal dependency" GUI library and just be straight and say "it requires SDL, OpenGL, or Direct3D"

because that's the current state of things.

**Comment by gek169** [comment]
> I recommend having a look around for other immediate-mode gui that suits your needs better. We don't really have the contributors available to make big architectural changes. So unless you intend to spearhead the effort of improving Nuklear for your needs, there is not much that can be do.
> 
> Best of luck :)

I couldn't find one, so I ended up writing one. Fairly barebones, but it suits my purposes.

I thought I could use your library, but I found out pretty quickly it was a shoddy, bloated waste of my time.

**Comment by dumblob** [comment]
>but it requires an RGBA display

It actually doesn't require an RGB display - but it does all computations internally with RGBA in mind. To be clear, most embedded displays nowadays are not 2bit per pixel, but more (e.g. to show at least few shades of gray). Speaking of which, Nuklear still **supports** black & white displays as perfectly as any other display (but it surely wastes some computation power in such use cases).

>Write a backend to write into a raw framebuffer given an array of pixels. Let me control how user input is polled and feed it into the library.

There is of course raw framebuffer backend with own control over input "polling" as you called it. Feel free to see both in https://github.com/Immediate-Mode-UI/Nuklear/blob/master/demo/x11_rawfb/ ([`nk_rawfb_init()`](https://github.com/Immediate-Mode-UI/Nuklear/blob/4a749821c46865e9592fe1437638d89f1b3409da/demo/x11_rawfb/nuklear_rawfb.h#L815 ) and [`nk_input_begin()` ... `nk_input_end()`](https://github.com/Immediate-Mode-UI/Nuklear/blob/4a749821c46865e9592fe1437638d89f1b3409da/demo/x11_rawfb/main.c#L202-L207 )).

>Don't require a ttf font to be loaded.

Just don't define `NK_INCLUDE_FONT_BAKING` and no TTF support will be included (and thus no ttf font should be required) :wink:.

>I've got a perfectly good 8x8 public domain header-only bitmap ascii font just for you:
>
>https://github.com/dhepper/font8x8

Thanks for suggestion! Sounds good - please make a PR as this would be a good feature to have (it should be orthogonal to `NK_INCLUDE_FONT_BAKING` so that both can be used together or separately or none of both).

Sometimes things are much easier than they look like on a first sight. We're awaiting your PR(s)! [Talk is cheap, show us the code!](https://en.wikiquote.org/wiki/Linus_Torvalds )

**Comment by gek169** [comment]
Thank you for the minor correction.
