### ISSUE TITLE
A question about the "does not have any dependencies" claim.

### ISSUE THREAD

**Issue by leojay** [Immediate-Mode-UI/Nuklear#291]
Hi, 

In the doc, it says that Nuklear "does not have any dependencies."
But when I run a sample binary in a freshly-installed Ubuntu 21.04 Desktop machine, it says:
```
$ ./extended
./extended: error while loading shared libraries: libglfw.so.3: cannot open shared object file: No such file or directory
```
Also, `ldd extended` clearly shows that there are a lot of dependencies.
How to build Nuklear applications without any dependencies as claimed in the doc?
Thanks!

Leo

**Comment by dumblob** [comment]
Nuklear is about layout, widgets, fonts, memory management, etc. The output of Nuklear is an in-memory list of Nuklear-specific "drawing instructions". But that's usually of no use if it doesn't get "interpreted" by the given specific machine with given specific routines for drawing (be it to a static bitmap picture, to a static vector picture, to a game framebuffer, to an X11 window, to a web canvas, to whatever...). We call these "interpreters" backends. And you happen to come across a complete example (i.e. tailored for some subset of machines unlike pure Nuklear which is machine-agnostic) which uses one chosen backend - namely glfw :wink:.

Nuklear hosts also many backends next to the lib itself. You'll find them in https://github.com/Immediate-Mode-UI/Nuklear/tree/master/demo .

Does this clarify all your concerns?

**Comment by leojay** [comment]
Hmm, I didn't notice that there was a `demo` directory. I tried the `x11` demo project and the binary ran in my freshly-installed Ubuntu 21.04 Desktop machine without any issues. 
I think the doc should be updated to clarify that Nuklear applications still depend on some backend to work. IMO, a simple "does not have any dependencies" is a little bit misleading.
Thanks for the help!

**Comment by dumblob** [comment]
>I think the doc should be updated to clarify that Nuklear applications still depend on some backend to work. IMO, a simple "does not have any dependencies" is a little bit misleading.

PRs welcome :wink:.

>I think the doc should be updated to clarify that Nuklear applications still depend on some backend to work. 

Believe me, Nuklear really does **not** depend on any backend to work. Nuklear really just computes the list of instructions and finishes without any errors. It's just that most people have no use of this list and need to visualize it somehow. That's why we provide also some useful backends for ordinary users :wink:. Note Nuklear is not a graphics library, it's a UI library. Unlike most GUI libraries which do not decouple anything and thus contain also (a very limited set of) chosen graphics libraries/drivers (or at least bindings to them on which they depend unlike Nuklear).
