### ISSUE TITLE
Update links

### ISSUE THREAD

**Issue by Nielsbishere** [Immediate-Mode-UI/Nuklear#3]
There's a few broken links since moving to Immediate-Mode-UI. These include the build system which still tries to build the old repo.

**Comment by dumblob** [comment]
Yeah, correct. PRs are welcome (I'm still short of time :cry:).

**Comment by englercj** [comment]
Is there a reason the repo wasn't moved so that github will forward all the old URLs?

**Comment by dumblob** [comment]
@englercj unfortunately [there is a reason](https://github.com/vurtun/nuklear/commit/ccb51f8ac1a1179d6b01ccd301f2071867af22ef#commitcomment-36173546 )

**Comment by englercj** [comment]
that is unfortunate :/

**Comment by the-grue** [comment]
Wouldn't it have been better to archive the original repo instead of deleting all the files?  Almost seems like an attempt to rewrite history...

**Comment by dumblob** [comment]
>Wouldn't it have been better to archive the original repo instead of deleting all the files?

Nobody has the permissions to do so. Only @vurtun has them (since it's his personal repository), but he is inactive for several years now. See also the [request to @vurtun from me](https://github.com/vurtun/nuklear/issues/941#issue-528607582 ) (as I'm the only one having contribution permissions in his personal repository, but I have no admin rights :cry:).

>Almost seems like an attempt to rewrite history...

Not sure what you mean. This new repository keeps the whole git history and I see no signs of "history rewriting" ([might be related](https://github.com/vurtun/nuklear/pull/913#issuecomment-558565788 )).

**Comment by Nielsbishere** [comment]
But couldn't you have left the old files there and updated the readme to point to the new repo? If people didn't copy the header themselves it would break if they get latest on the submodule

**Comment by dumblob** [comment]
>But couldn't you have left the old files there and updated the readme to point to the new repo? If people didn't copy the header themselves it would break if they get latest on the submodule

That's the plan (it's part of [programming best practices](https://stackoverflow.com/questions/2807241/what-does-the-expression-fail-early-mean-and-when-would-you-want-to-do-so )).

**Comment by the-grue** [comment]
> Not sure what you mean. This new repository keeps the whole git history and I see no signs of "history rewriting"

Yes, you kept the git history.  But you didn't base this off a fork, for one thing, you abandoned all the issues and outstanding pull requests for another.  Also, deleting all of the files from the original author's repo makes this seem more like a hostile takeover than a "we want to go in our own direction because the original author is no longer available".

It just doesn't sit well with me and I would imagine I am not alone.  I discovered and forked the original repo a couple weeks ago and before I got a chance to do anything with it I see all the files are gone and now there is this site.  I understand what you are trying to do, I just disagree with the way you are going about it in respect to @vurtun 's repo.

I would just like to recommend that you reset @vurtun 's repo back to the October 1, 2019 commit (adc52d7), update the readme file to point to this site, and move on.

**Comment by dumblob** [comment]
@the-grue it seems we're talking at cross purposes. @vurtun said, that he has no more time to maintain his repository few years ago. He gave me (and maybe also someone else who was also inactive for years) contribution permission to his repository. His repository can't be any more the project main repository (can't scale), so we moved the project elsewhere.

We **deliberately** did not fork anything, but stopped knitting the old chord and started from that point at a different place. Forking means just making a new remote branch, but that would mean few dudes are trying to do things their way, which is not true at all - we just want to continue. Btw. did it even appear to you it's impossible to fork a repository as an organization?

1. The best option would be to use the GitHubs functionality to move the repo.
2. The second best option is to follow [best practices](https://stackoverflow.com/questions/2807241/what-does-the-expression-fail-early-mean-and-when-would-you-want-to-do-so ).

The option (1) wasn't available, so we went with (2). No need to get emotional or think off some takeover fairy tales - it's plain rational choice.

Btw. now the repo https://github.com/vurtun/nuklear is archived (thanks @vurtun!) and has some content.

----
If it's difficult for you to change remote branch in your already cloned repository or whatever, then tell us and you'll get some help. It's though dead easy under usual conditions, so I assume that wasn't the reason for this discussion.

**Comment by englercj** [comment]
> We deliberately did not fork anything, but stopped knitting the old chord and started from that point at a different place.

That is the definition of a fork. The author left, and you continued development elsewhere. That is a fork. You made a fork here manually, you just didn't let GitHub link back to the original repository.

> Forking means just making a new remote branch, but that would mean few dudes are trying to do things their way, which is not true at all - we just want to continue.

That's not what a fork is. A fork doesn't imply a "few dudes are trying to do things their way". It just means this repo continues elsewhere outside the original one, with the original link maintained for historical purposes.

The only logistical reason not to do a real fork would be the GitHub search mechanics. Not optics.

> Btw. did it even appear to you it's impossible to fork a repository as an organization?

You can definitely fork a repo into an org. I've done it myself, and it is mentioned in the [docs](https://help.github.com/en/github/getting-started-with-github/fork-a-repo#find-another-repository-to-fork):

>You can fork any public repository to your user account or any organization in which you have repository creation permissions. For more information, see "[Permission levels for an organization](https://help.github.com/en/articles/permission-levels-for-an-organization)."

Also, just because it is bothering me: Fail Fast refers to a situation in which if there is a problem, you should fail early so it is visible. This situation doesn't really fall into that category. The submodules to the old repo would've continued to work fine. My web links to the code files would've continued to work fine. There was no problem. You created a new problem to catch people's attention so they moved to the new remote, even when they didn't need to. That was unnecessary.

> No need to get emotional or think off some takeover fairy tales - it's plain rational choice.

No need to get so defensive about some well intentioned advice. Deleting the code and starting a new repository of the same name certainly has the image that you were just taking the code and erasing the history of where it came from.

**Comment by dumblob** [comment]
>That is the definition of a fork. The author left, and you continued development elsewhere. That is a fork. You made a fork here manually, you just didn't let GitHub link back to the original repository.

I must disagree here. There is at least 100 authors (and they spent together more time with Nuklear than @vurtun). So not a fork at all. Just permission issue.

>The only logistical reason not to do a real fork would be the GitHub search mechanics. Not optics.

Disregarding search mechanics, the risk is very high, that a non-archived repo will make everybody using any automation tooling to stick with the original unmainted repo. Nobody knew when - and if so - @vurtun will appear again and archive the original repo after those years of inactivity. You can't let users think that their automation tools fetch the newest master if they won't. The smart users fetching a particular commit are **unaffected**.

>You can definitely fork a repo into an org. I've done it myself, and it is mentioned in the docs:
> ...

**Comment by the-grue** [comment]
Ignoring the insults and negativity.  

Thanks @vurtun for archiving your original repo and making the files visible again.

Carry on folks and best of luck!

**Comment by Nielsbishere** [comment]
https://github.com/Immediate-Mode-UI/Nuklear/pull/10

**Comment by Nielsbishere** [comment]
Solved in PR https://github.com/Immediate-Mode-UI/Nuklear/pull/10, using GitHub CI instead.
