### ISSUE TITLE
Node editor - is the advertised GIF implemented?

### ISSUE THREAD

**Issue by crazyBaboon** [Immediate-Mode-UI/Nuklear#303]
Hi,

I was having a look at the node editor and, to the best of my knowledge, I cannot find 
how to **delete/rename/copy** nodes, as can be seen in the advertised GIF:

![Screenshot from 2021-05-30 11-33-40](https://user-images.githubusercontent.com/19549703/120101205-ca3b1400-c13c-11eb-95b4-49e8ea530a49.png)

The GIF leaves the impression those actions are possible but it does not actually show them being carried out.

Are these actions possible like the GIF suggests?

Thanks!

**Comment by FrostKiwi** [comment]
> Are these actions possible like the GIF suggests?
> 
> Thanks!

As written in the node_editor.c file, that implements this demo...
https://github.com/Immediate-Mode-UI/Nuklear/blob/d829ff1ef1e84d4ee46c600d228d1a274923ed07/demo/node_editor.c#L2-L12 ...it is just for demo purposes, especially in regards to drawing splines. Those copy-paste functions were probably from someone doing platform specific things and were cut away to be included in a simple demo, which should work on any platform. This library is supposed to provide just the widget functions and not specific implementations of User Interfaces, since that would balloon the scope, so that node editor demo is not actually meant to be used seriously.

Someone else did work on creating a more fully featured node_editor.c: https://github.com/h33p/Nuklear-Node-Editor
I have never tried it myself though.
