### ISSUE TITLE
Would Nuklear be a good fit for a spreadsheet like program?

### ISSUE THREAD

**Issue by uvuxz** [Immediate-Mode-UI/Nuklear#329]
Hi!

Great project! 

I have written a small in-memory database and would like to make a GUI, in spreadsheet style, to see/edit the data within.
Do you think Nuklear would be a good fit for the task or should I look into other libraries?

All the best.

**Comment by dumblob** [comment]
I think it would. But of course, it depends on your needs - e.g. Nuklear could become inefficient for millions of long entries because it doesn't optimize complex scrollable regions.

The advantage of Nuklear is that you can try it enormously quickly to see whether it serves the purpose you expect or not. I think such a demo app should be feasible to code in 1-3 hours for a newcomer.
