### ISSUE TITLE
Discord server

### ISSUE THREAD

**Issue by jackghg** [Immediate-Mode-UI/Nuklear#367]
is there a community ? like irc , discord, telegram... add it to the readme

**Comment by RobLoach** [comment]
@dumblob @jackghg The Nuklear community is pretty small so unsure how valuable it would be, but mocked up a quick Discord server for it over here:
https://discord.gg/M3QKFsUdaV

**Comment by jackghg** [comment]
Well done!

**Comment by RobLoach** [comment]
Going to open this issue to have some discussion around it. Would love a few moderators too, if we are going to make it an actual thing. Need to post it elsewhere on the readme too.

**Comment by dumblob** [comment]
Yep. That's the reason we didn't establish any chat-like platform - we barely have time to review PRs, we seldom come to discuss even important issues here in the tracker, so maintenance and moderation of some discussion board or chat or whatever is just a crazy joke.

But if there are at least two persons who will:
1. create & maintain the chat/discussion_board/... technically (incl. updating readme here in this repo)
2. moderate it/them actively 24/365
3. actively seek for new moderators
3. close/freeze it/them technically (incl. updating readme here in this repo) in case they won't have the time any more and no 2 moderators will step up

Then I'm all for it (I myself can't be a moderator though due to my life duties :wink:)!

**Comment by RobLoach** [comment]
It lives!
