### ISSUE TITLE
[Question] How to delete programmatically a window?

### ISSUE THREAD

**Issue by blojkr74** [Immediate-Mode-UI/Nuklear#404]
I am working with gflw_opengl2 and I have two windows: "Demo" and "Overview".

I am trying to delete the "Overview" window when i press the button on the "Demo" window:

**if (nk_button_label(ctx, "button"))
{            
    nk_window_close(ctx, "Overview"); 
    fprintf(stdout, "button pressed\n");
}**

This approach does not work though, since when I click the button in the "Demo" window, 
the "Overview" window simply gets re-positioned to its original position.

Any idea on how to do this?

Thanks!

**Comment by RobLoach** [comment]
Set a `bool`, and toggle it when you hit that function.

**Comment by blojkr74** [comment]
@RobLoach do you know why the "Overview" window gets re-positioned rather than deleted?

**Comment by FrostKiwi** [comment]
> @RobLoach do you know why the "Overview" window gets re-positioned rather than deleted?
> 
> Could you add a bit of detail to your `bool` suggestion?
> 
> Thanks!

It does not get repositioned. It gets *recreated from scratch*, because your GUI definiton gets called again. That's why it looks like it get's repositioned.

´nk_window_close()´ unbinds the hash that is connected to the window name "Overview". The internal garbage collector then frees all resources connected to that hash.
This is in contrast to ´nk_window_show(ctx, "Settings", NK_HIDDEN);´, which hides the window without deleteing the window hash and freeing it's resources. But then your code again goes over the definition of that window and creates it again.

You have to stop redefining the window you want to close. One way to do this is to #include your seperate window and stop the inclusion once you want it deleted, or wrap everything in a huge if statement. That is what @RobLoach meant with the bool. This may seem cumbersome, but that's Immeadiate mode for you. No state. Not even state to remember the fact which windows were deleted ;]

**Comment by dumblob** [comment]
Speaking of state, there is at least one way how to manage state in a "readable" modular (as in "separation of concerns" and "maintain locality") fashion which seems 100% compatible with immediate mode libraries like Nuklear.

Namely rule-based state management as e.g. demonstrated in https://github.com/paranim/pararules (but you'd need to write [advanced macros if you used Nuklear with pure C](https://github.com/Hirrolot/metalang99 ) as otherwise it'd be quite some boilerplate partially defeating the purpose of using rules for state management).

If you tried it, let us know as that'd be a really cool demo I'd very much like to have in this repo!

**Comment by blojkr74** [comment]
Many thanks @RobLoach and @dumblob!

That approach works, I have tested it.
