### ISSUE TITLE
[QUESTION] compile without single file ?

### ISSUE THREAD

**Issue by jacknicklenson** [Immediate-Mode-UI/Nuklear#416]
is it possible to use nuklear without single file, like using as is in the src/*.c source files ? if yes can you walkthrough because i could not make it :/

**Comment by dumblob** [comment]
Did you manage to solve it? Could you describe what was the culprit?

If it still doesn't work for you, feel free to reopen this issue. Thanks!

**Comment by jacknicklenson** [comment]
sorry, when nobody answered, i thought nobody interested or a silly question so i decided to close and still i cannot manage to work it. My goal is use library as a seperate c files rather than single header. I think its because of ifdefs but i am not sure, library is designed in a single header file logic, when compiling seperate c files, lots of undefined symbols error happining for  example MEMCPY, SIN, COS,.... etc.

thx for interest :)

**Comment by dumblob** [comment]
Did you take a look at all `examples/` and `demos/`? There are some which use multiple files.

It's also important to follow everything in [**Building**](https://github.com/Immediate-Mode-UI/Nuklear#building ) in the readme.

**Comment by jacknicklenson** [comment]
sorry i think i cannot express myself clearly, i know how to include library, compile and use, i even created a ui by using this library but my point is not using 1.2MB sized nuklear.h with its corresponding backend, i want to compile & use this library with seperated .c file in the `src/` folder, like ```src/nuklear_panel.c, src/nuklear_window.c.... etc```.

BTW demo and example folders, all use single header one which is 1.2MB, not seperated *.c files.

thx for interest again

**Comment by dumblob** [comment]
Ahah, now I see! Well, that's probably for the first time someone came with this request :wink:.

The individual files in `src/` are not self-contained and meant for simple concatenation into single `nuklear.h` file. So there'll definitely be needed some adjustments to use them separately without prior concatenation.

What's the motivation to not use `nuklear.h` but all the individual files individually?

If it's speed of compilation, then you shouldn't gain anything by using separate files (actually it should be slower due to more disk seeking needed due to many files instead of one) as it's guaranteed to be included (i.e. read, parsed, compiled) only once.
