### ISSUE TITLE
glfw opengl4 not working in mac

### ISSUE THREAD

**Issue by mahaidong** [Immediate-Mode-UI/Nuklear#6]
Error 65543: Requested OpenGL version 4.5, got version 4.1

**Comment by dumblob** [comment]
Please provide more information (post your source code to pastebin, tell us which operating system and which versions of software you're using, etc.).

**Comment by mahaidong** [comment]
system:  macos 10.15.1   MacBook Pro (Retina, 13-inch, Late 2012)
I can compile the demo code  <Nuklear>/demo/glfw_opengl4

then i `./bin/demo` in terminal , I got this information: 
Error 65543: Requested OpenGL version 4.5, got version 4.1

**Comment by dumblob** [comment]
Thanks. In that case the backend (everything under `demo/` are different backends) is not supported on your platform of choice (macOS). Feel free to choose other backends or make sure your systems is compatible with the `glfw_opengl4` backend.

**Comment by mahaidong** [comment]
> Thanks. In that case the backend (everything under `demo/` are different backends) is not supported on your platform of choice (macOS). Feel free to choose other backends or make sure your systems is compatible with the `glfw_opengl4` backend.

almost all mac computer only support opengl4.1.
https://support.apple.com/en-us/HT202823

**Comment by dumblob** [comment]
Well, that's the point of having backends in Nuklear - you can choose for your project which specific backend you'd like to use (you can of course use different backends in one project and choose at compile time or at run time - this is allowed due to backend agnostic API Nuklear provides).

Nuklear will by no means choose a backend for you - we don't even provide any backends and all of them are user contributions (that's why the directory is called `demos/` and not `backends/` as those are just show cases how to use Nuklear in some specific cases).
